#!/usr/bin/env bash

if command -v fd >/dev/null 2>&1; then
  fd -e mp4 -e avi -e mkv -e mov -e wmv -e flv -e webm -e m4v -e mpg -e mpeg -e 3gp -e ogv -e asf -e rm -e rmvb -e vob -e ts -e mts -e m2ts -e f4v
else
  find . -type f \( -iname "*.mp4" -o -iname "*.avi" -o -iname "*.mkv" -o -iname "*.mov" -o -iname "*.wmv" -o -iname "*.flv" -o -iname "*.webm" -o -iname "*.m4v" -o -iname "*.mpg" -o -iname "*.mpeg" -o -iname "*.3gp" -o -iname "*.ogv" -o -iname "*.asf" -o -iname "*.rm" -o -iname "*.rmvb" -o -iname "*.vob" -o -iname "*.ts" -o -iname "*.mts" -o -iname "*.m2ts" -o -iname "*.f4v" \) 2>/dev/null
fi
