#!/usr/bin/env bash

if command -v fd >/dev/null 2>&1; then
  fd -e jpg -e jpeg -e png -e gif -e bmp -e tiff -e tif -e webp -e svg -e ico -e heic -e heif -e raw -e cr2 -e nef -e arw -e dng -e psd -e xcf
else
  find . -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" -o -iname "*.bmp" -o -iname "*.tiff" -o -iname "*.tif" -o -iname "*.webp" -o -iname "*.svg" -o -iname "*.ico" -o -iname "*.heic" -o -iname "*.heif" -o -iname "*.raw" -o -iname "*.cr2" -o -iname "*.nef" -o -iname "*.arw" -o -iname "*.dng" -o -iname "*.psd" -o -iname "*.xcf" \) 2>/dev/null
fi
