#!/usr/bin/env bash

if ! command -v gs &>/dev/null; then
    echo "Ghostscript (gs) is not installed. Please install it to use this script."
    exit 1
fi

if [ "$1" = "-ebook" ]; then
    PDF_SETTINGS="/ebook"
    INPUT_FILE="$2"
else
    PDF_SETTINGS="/screen"
    INPUT_FILE="$1"
fi

if [ -z "$INPUT_FILE" ]; then
    echo "No input file specified. Please provide the PDF file as an argument."
    exit 1
fi

gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS="$PDF_SETTINGS" -dNOPAUSE -dBATCH -sOutputFile="optimised-${INPUT_FILE}" "$INPUT_FILE"
