#!/usr/bin/env bash

display_help() {
    echo "Usage: $(basename "$0") <image_dir> [small|medium|large] [quality]" >&2
    echo "Generate three downscaled copies of each image in a directory." >&2
    exit 1
}

if [[ "$1" == "-h" || "$1" == "--help" || -z "$1" ]]; then
    display_help
fi

if ! command -v magick &>/dev/null; then
    echo "ImageMagick is not installed. Please install it to use this script." >&2
    exit 1
fi

IMAGE_DIR="$1"

# Define the three default dimensions to which the images should be compressed
SMALL_DIMENSIONS=(800x600 640x480 320x240)
MEDIUM_DIMENSIONS=(1024x768 800x600 640x480)
LARGE_DIMENSIONS=(1600x1200 1280x960 1024x768)

# Check if the user has specified small, medium, or large images
if [[ "$2" == "small" ]]; then
    DIMENSIONS=("${SMALL_DIMENSIONS[@]}")
elif [[ "$2" == "medium" ]]; then
    DIMENSIONS=("${MEDIUM_DIMENSIONS[@]}")
elif [[ "$2" == "large" ]]; then
    DIMENSIONS=("${LARGE_DIMENSIONS[@]}")
else
    # Use the default dimensions if no optional parameter is specified
    DIMENSIONS=("${MEDIUM_DIMENSIONS[@]}")
fi

# quality setting
if [ -n "$3" ] && [ "$3" -eq "$3" ] 2>/dev/null; then
    QUAL=$3
else
    QUAL=90
fi

# Create the compressed directory if it doesn't exist
mkdir -p "${IMAGE_DIR}/compressed"

LABELS=(lg md sm)

# Loop through the dimensions and compress the images
for IDX in "${!DIMENSIONS[@]}"; do
    SIZE="${DIMENSIONS[$IDX]}"
    LABEL="${LABELS[$IDX]}"
    # Loop through the images in the directory
    for FILE in "${IMAGE_DIR}"/*.*; do
        # Get the file extension
        EXTENSION="${FILE##*.}"

        # Check if the file is an image
        if [[ "$EXTENSION" =~ ^(jpg|jpeg|png|gif|avif|webp)$ ]]; then
            # Get the file name without the extension
            FILENAME="${FILE%.*}"

            # Convert the file name to a slug
            SLUG="$(slugify "$(basename "${FILENAME}")")"

            echo "resized $FILE $QUAL $SIZE"
            # Use ImageMagick to resize the image to the specified dimensions and save it to the compressed directory
            magick "${FILE}" -resize "${SIZE}^" -quality "${QUAL}" -extent "${SIZE}" "${IMAGE_DIR}/compressed/${SLUG}_${LABEL}.${EXTENSION}"
        fi
    done
done
